--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    advisor_last_contact_at timestamp with time zone,
    has_newsletter boolean,
    status text,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    -- Lead pipeline stage (S1..S10 or 'descartado'). A contact IS the lead in
    -- Inmovel, so the pipeline stage lives here. Sync-owned while in S1..S5.
    stage text,
    -- When the lead last entered its current stage. Set by the
    -- set_stage_changed_at trigger on any stage change; drives the kanban timer.
    stage_changed_at timestamptz default now(),
    -- Inmovel lead fields mirrored from the Sheet Leads tab (sync-owned;
    -- written only by the sheet sync, read-only in the CRM UI).
    canal text,
    fuente text,
    nombre text,
    nombre_completo text,
    telefono text,
    estado text,
    desarrollos jsonb,
    desarrollo_activo text,
    ad_id text,
    zona_interes text,
    presupuesto text,
    tipo_busqueda text,
    total_mensajes integer,
    historial_json jsonb,
    ventana_compra text,
    forma_compra text,
    credito_status text,
    fecha_visita_propuesta timestamp with time zone,
    intencion_visita boolean,
    -- Advisor owning this lead; FK to sales for RLS (TASK-014). The sheet
    -- sync resolves the sheet's advisor phone to a sales id on upsert.
    asesor_asignado bigint,
    mensajes_post_handoff integer,
    resumen_sales text,
    renta_seleccion_pendiente integer,
    renta_seleccion_confirmada boolean,
    propiedad_interes jsonb,
    asesor_externo text,
    asesor_externo_tel text,
    alerta_broker_externo_enviada boolean,
    fecha_transicion_consultor timestamp with time zone,
    fecha_ultimo_contacto timestamp with time zone,
    -- CRM-owned lead fields (never touched by the sheet sync)
    handoff_trigger text,
    motivo_descarte text,
    -- Sheet lead id (string key from the Google Sheet); the one-way sync keys
    -- upserts on this so it stays idempotent. Null for CRM-created contacts.
    sheet_id text unique
);

-- Property inventory: own developments plus shared/broker (NocNok) listings.
-- Synced one-way from the Sheet Propiedades tab; read-only in the CRM.
create table public.propiedades (
    id text primary key,
    tipo text not null,
    nombre text not null,
    estatus text,
    operacion text,
    direccion text,
    colonia text,
    alcaldia text,
    precio numeric,
    metros numeric,
    recamaras numeric,
    banos numeric,
    estacionamiento numeric,
    pet_friendly text,
    argumento1 text,
    argumento2 text,
    argumento3 text,
    lista_precios text,
    url_anuncio text,
    url_maps text,
    tipos_unidades text,
    precios_por_tipo text,
    caracteristicas text,
    amenidades text,
    argumentos_zona text,
    esquema_pago text,
    creditos text,
    objeciones text,
    precio_desde numeric,
    precio_hasta numeric,
    m2_desde numeric,
    m2_hasta numeric,
    recamaras_min numeric,
    recamaras_max numeric,
    unidades_disponibles text,
    fecha_entrega text,
    enganche_minimo_pct text,
    features text,
    destacado text,
    url_ficha text,
    codigo_fuente text,
    fuente text,
    broker_nombre text,
    broker_telefono text,
    broker_wa text,
    comision text,
    activa boolean default true,
    orden numeric,
    fecha_carga text,
    account_name text,
    account_id text,
    shared_commission text,
    status_days text,
    is_exclusive boolean default false,
    share_type text,
    -- Drive folder with marketing material: own properties point to a folder in
    -- the Inmovel Drive; GDC properties reference their CLIENTES EXTERNOS subfolder.
    material_url text
);

-- Advisor-recorded visit (CRM-owned; never touched by the sheet sync).
create table public.visitas (
    id bigint generated by default as identity primary key,
    lead_id bigint not null references public.contacts(id) on delete cascade,
    propiedad_id text references public.propiedades(id),
    fecha timestamp with time zone not null,
    resultado text,
    notas text,
    asesor_id bigint,
    created_at timestamp with time zone not null default now(),
    -- Google Calendar event id: the visit is created as a calendar event (source
    -- of truth) and mirrored here; this keys the Calendar<->CRM sync.
    gcal_event_id text unique,
    -- Mirrored from the calendar event status (confirmada | cancelada). The
    -- calendar_sync sets this; resultado/notas stay CRM-owned.
    estado text default 'confirmada'
);

create index visitas_lead_id_idx on public.visitas using btree (lead_id);

-- M:N lead <-> property relation (synced; relacion explains the link origin).
create table public.lead_propiedad (
    id bigint generated by default as identity primary key,
    lead_id bigint not null references public.contacts(id) on delete cascade,
    propiedad_id text not null references public.propiedades(id) on delete cascade,
    relacion text not null,
    unique (lead_id, propiedad_id, relacion)
);

-- Bot transcript (append-only, synced from the Sheet; read-only in the CRM).
create table public.conversaciones (
    id bigint primary key,
    lead_id bigint not null references public.contacts(id) on delete cascade,
    rol text not null,
    texto text,
    timestamp timestamp with time zone,
    nombre_lead text
);

create index conversaciones_lead_id_timestamp_idx
    on public.conversaciones using btree (lead_id, timestamp);

-- Lead search profile extracted from the WhatsApp transcript by the
-- lead-profile-extract job (Haiku). One row per lead; feeds the Property Matcher
-- (lead_property_matches view). Private per-lead intent — RLS-scoped to the lead
-- owner in 05_policies.sql, exactly like conversaciones.
create table public.lead_match_profile (
    lead_id bigint primary key references public.contacts(id) on delete cascade,
    operacion text,
    zonas text[],
    presupuesto_min numeric,
    presupuesto_max numeric,
    recamaras int,
    tipo text,
    confianza numeric,
    evidencia text,
    fuente text,
    model text,
    raw jsonb,
    extracted_at timestamp with time zone default now()
);

-- Meta ad -> property mapping (synced reference, read-only).
create table public.anuncios (
    ad_id text primary key,
    ad_name text,
    propiedad_id text,
    activo boolean default true,
    created_at timestamp with time zone
);

-- External NocNok feed mirror (synced raw reference; not a CRM section).
create table public.nocnok_raw (
    codigo text primary key,
    nocnok_id text,
    operacion text,
    precio numeric,
    category text,
    type text,
    type_text text,
    recamaras numeric,
    full_bathrooms numeric,
    half_bathrooms numeric,
    m2 numeric,
    lot_size numeric,
    colonia text,
    alcaldia text,
    estado text,
    cp text,
    estacionamiento numeric,
    year_built text,
    levels text,
    title text,
    url_ficha text,
    lat text,
    lon text,
    account_name text,
    account_id text,
    account_plan text,
    shared_commission text,
    is_exclusive boolean default false,
    share_type text,
    status_days text,
    status_date text,
    fotos numeric,
    activa boolean default false,
    orden numeric,
    fecha_carga text,
    broker_tel text,
    broker_wa text
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[],
    -- sales ids to notify about this note (@mention). A trigger fans these out
    -- into note_mentions rows (one per recipient, with read state).
    mentions bigint[]
);

-- Per-recipient @mention notification with read state. Spawned by a trigger
-- from contact_notes.mentions; the CRM reads/updates it (bell + "leído").
create table public.note_mentions (
    id bigint generated always as identity primary key,
    note_id bigint references public.contact_notes(id) on delete cascade,
    contact_id bigint references public.contacts(id) on delete cascade,
    recipient_id bigint references public.sales(id),
    sender_id bigint references public.sales(id),
    created_at timestamptz default now(),
    read_at timestamptz
);

create index note_mentions_recipient_unread_idx
    on public.note_mentions(recipient_id) where read_at is null;

-- Small server-side config store (e.g. the notify_mention shared secret). RLS is
-- enabled with no policies so it is unreadable except by SECURITY DEFINER
-- functions / the service role. Values are set at runtime, never committed.
create table public.app_config (
    key text primary key,
    value text
);

-- Reactivation cohorts: phone numbers that received an out-of-pipeline WhatsApp
-- reactivation template, with the cohort and template they got. Materializes the
-- bot's hardcoded REACTIVACION_TELS guard. When such a lead replies, the
-- create_reactivation_note trigger surfaces the reply as a note on the ficha.
create table public.reactivaciones (
    telefono text primary key,
    grupo text,
    template text,
    fecha date default now()
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    -- Inmovel asesor fields (mirrored from the Sheet Asesores tab by the sync)
    telefono text,
    -- WhatsApp number in E.164 (52155...) for mention notifications. `telefono`
    -- is the synced display number (often without country code), so this holds
    -- the send-ready form.
    whatsapp text,
    calendario text,
    linea_negocio text check (linea_negocio in ('exclusiva', 'compartida')),
    activo boolean default true,
    -- Advisors are assigned to a manager; the manager team-scope RLS
    -- (TASK-014) reads leads whose asesor_asignado has this manager_id.
    manager_id bigint references public.sales(id)
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);

-- Inmovel FK constraints (added after table creation to avoid forward refs)
alter table public.contacts
    add constraint contacts_asesor_asignado_fkey foreign key (asesor_asignado) references public.sales(id);

alter table public.visitas
    add constraint visitas_asesor_id_fkey foreign key (asesor_id) references public.sales(id);
