--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    -- Lead pipeline stage (S1..S10 or 'descartado'). A contact IS the lead in
    -- Inmovel, so the pipeline stage lives here. Sync-owned while in S1..S5.
    stage text,
    -- Inmovel lead fields mirrored from the Sheet Leads tab (sync-owned;
    -- written only by the sheet sync, read-only in the CRM UI).
    canal text,
    fuente text,
    nombre text,
    nombre_completo text,
    telefono text,
    estado text,
    desarrollos jsonb,
    desarrollo_activo text,
    ad_id text,
    zona_interes text,
    presupuesto text,
    tipo_busqueda text,
    total_mensajes integer,
    historial_json jsonb,
    ventana_compra text,
    forma_compra text,
    credito_status text,
    fecha_visita_propuesta timestamp with time zone,
    intencion_visita boolean,
    -- Advisor owning this lead; FK to sales for RLS (TASK-014). The sheet
    -- sync resolves the sheet's advisor phone to a sales id on upsert.
    asesor_asignado bigint references public.sales(id),
    mensajes_post_handoff integer,
    resumen_sales text,
    renta_seleccion_pendiente integer,
    renta_seleccion_confirmada boolean,
    propiedad_interes jsonb,
    asesor_externo text,
    asesor_externo_tel text,
    alerta_broker_externo_enviada boolean,
    fecha_transicion_consultor timestamp with time zone,
    fecha_ultimo_contacto timestamp with time zone,
    -- CRM-owned lead fields (never touched by the sheet sync)
    handoff_trigger text,
    motivo_descarte text
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
