-- Conversaciones cutover (Sheet -> Supabase): the bot writes messages straight
-- to Supabase instead of the Sheet. To keep the bot id space disjoint from the
-- Sheet's low sequential ids (still upserted by sheet_sync for historical rows
-- and any fallback writes), turn id into an identity column that starts at 1e9.
--
-- GENERATED BY DEFAULT (not ALWAYS) is required so sheet_sync can keep inserting
-- explicit low ids for historical rows without erroring. Idempotent.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'conversaciones'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.conversaciones
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH 1000000000);
  END IF;
END $$;
